// GAMBLE.IO HOTFIX — no Firebase imports required for guest play.
const $ = (s) => document.querySelector(s);
const entry = $('#entry'), tour = $('#tour'), app = $('#app'), view = $('#view');
let chips = Number(localStorage.getItem('gambleChips') || 10000);
let dev = localStorage.getItem('gambleDev') === 'true';
const games = [['🎲','Dice Duel'],['🃏','Blackjack'],['🎰','Slots'],['🏇','Horse Races'],['🎡','Roulette'],['🪙','Coin Flip'],['🎯','Hi-Lo'],['💎','Gem Drop'],['🎁','Mystery Box'],['🍀','Lucky 7'],['🃏','Poker Draw'],['🎳','Pin Strike'],['🚀','Rocket Run'],['🎪','Wheel Spin'],['🐟','Fishing Luck'],['🏀','Free Throw'],['🎴','Baccarat'],['🔴','Plinko'],['⭐','Star Match'],['👑','Royal Vault']];
function show(el){el.hidden=false} function hide(el){el.hidden=true}
function update(){ $('#chips').textContent = Math.floor(chips).toLocaleString(); localStorage.setItem('gambleChips', chips) }
function change(n){ chips=Math.max(0,chips+n);update() }
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2000)}
function openDoors(){ entry.classList.add('opening'); setTimeout(()=>{hide(entry);show(tour);setTimeout(openLobby,2200)},1450) }
function openLobby(){hide(tour);show(app);update();lobby()}
$('#enter').onclick=openDoors; $('#guest').onclick=openDoors;
const skip = $('#enterLobby'); if(skip) skip.onclick=openLobby;
$('#out').onclick=()=>{localStorage.removeItem('gambleChips');location.reload()};
document.addEventListener('click',e=>{let b=e.target.closest('[data-view]');if(b)({lobby,shop,leaderboard,terminal}[b.dataset.view])()});
function bet(){return `<label>Wager <input id="bet" type="number" min="1" max="${chips}" value="100"></label>`}function getBet(){let n=+$('#bet').value;return Number.isInteger(n)&&n>0&&n<=chips?n:null}function panel(title,html,cls='panel'){view.innerHTML=`<section class="${cls}"><button id="back">← Games</button><h2>${title}</h2>${html}</section>`;$('#back').onclick=lobby}
function lobby(){view.innerHTML=`<section class="hero"><h2>Pick a table.</h2><p>Virtual chips only. Your guest balance saves in this browser.</p></section><section class="grid">${games.map((g,i)=>`<button class="game" data-game="${i}"><span class="icon">${g[0]}</span><b>${g[1]}</b><small>Play now</small></button>`).join('')}</section>`;document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>play(+b.dataset.game))}
function play(i){let g=games[i][1];if(g==='Dice Duel')return dice();if(g==='Slots')return slots();if(g==='Horse Races')return horse();if(g==='Blackjack')return blackjack();if(g==='Roulette')return roulette();if(g==='Plinko')return plinko();panel(g,`${bet()} <button id="go" class="gold">Play</button><p id="result"></p>`);$('#go').onclick=()=>{let b=getBet();if(!b)return toast('Enter a valid wager.');let w=Math.random()<.46;change(w?b:-b);$('#result').textContent=w?`You won ${b} chips!`:`You lost ${b} chips.`}}
function dice(){panel('🎲 Dice Duel',`<p>Low wins 1–2. Exact wins only 3. High wins 4–6.</p>${bet()}<div class="row"><button data-p="low">Low 1–2</button><button data-p="exact">Exact 3</button><button data-p="high">High 4–6</button></div><p id="result"></p>`);document.querySelectorAll('[data-p]').forEach(x=>x.onclick=()=>{let b=getBet();if(!b)return toast('Enter a valid wager.');let r=1+(Math.random()*6|0),p=x.dataset.p,w=(p==='low'&&r<=2)||(p==='exact'&&r===3)||(p==='high'&&r>=4),d=w?b*(p==='exact'?5:1):-b;change(d);$('#result').textContent=`Rolled ${r}. ${w?`Won ${d} chips!`:`Lost ${b} chips.`}`})}
function slots(){panel('🎰 Neon Slots',`${bet()} <button id="spin" class="gold">Spin reels</button><div id="machine" class="slots"><span class="reel">🍒</span><span class="reel">🔔</span><span class="reel">💎</span></div><p id="result"></p>`);$('#spin').onclick=()=>{let b=getBet();if(!b)return toast('Enter a valid wager.');let m=$('#machine'),a=['🍒','🍋','🔔','💎','7️⃣'];m.classList.add('spinning');let t=setInterval(()=>document.querySelectorAll('.reel').forEach(x=>x.textContent=a[Math.random()*a.length|0]),80);setTimeout(()=>{clearInterval(t);let r=[a[Math.random()*5|0],a[Math.random()*5|0],a[Math.random()*5|0]];document.querySelectorAll('.reel').forEach((x,i)=>x.textContent=r[i]);m.classList.remove('spinning');let mult=r[0]===r[1]&&r[1]===r[2]?8:(r[0]===r[1]||r[1]===r[2]||r[0]===r[2]?1:0);change(mult?b*mult:-b);$('#result').textContent=mult?`Match! Won ${b*mult} chips.`:`No match. Lost ${b} chips.`},1050)}}
function horse(){panel('🏇 Horse Races',`${bet()}<div class="row">${[1,2,3,4].map(i=>`<button data-h="${i}">Bet Horse ${i}</button>`).join('')}</div><div class="race-track">${[1,2,3,4].map(i=>`<div id="horse${i}" class="horse">🏇 Horse ${i}</div>`).join('')}</div><p id="result"></p>`);document.querySelectorAll('[data-h]').forEach(x=>x.onclick=()=>{let b=getBet();if(!b)return toast('Enter a valid wager.');let winner=1+(Math.random()*4|0);[1,2,3,4].forEach(i=>$('#horse'+i).style.transform=`translateX(${i===winner?Math.min(500,innerWidth*.4):Math.random()*130}px)`);setTimeout(()=>{let w=+x.dataset.h===winner;change(w?b*3:-b);$('#result').textContent=`Horse ${winner} wins. ${w?`Won ${b*3} chips!`:`Lost ${b} chips.`}`},1450)})}
function roulette(){panel('🎡 Roulette',`${bet()} <button data-c="red">Red</button><button data-c="black">Black</button><p id="result"></p>`);document.querySelectorAll('[data-c]').forEach(x=>x.onclick=()=>{let b=getBet();if(!b)return toast('Enter a valid wager.');let c=Math.random()<.5?'red':'black',w=c===x.dataset.c;change(w?b:-b);$('#result').textContent=`Ball: ${c}. ${w?'You win!':'You lose.'}`})}
function plinko(){let pegs=Array.from({length:35},(_,i)=>`<i class="peg" style="left:${35+(i%7)*60}px;top:${35+Math.floor(i/7)*48}px"></i>`).join('');panel('🔴 Plinko',`${bet()} <button id="drop" class="gold">Drop chip</button><div id="board" class="plinko">${pegs}</div><p id="result"></p>`);$('#drop').onclick=()=>{let b=getBet();if(!b)return toast('Enter a valid wager.');let c=document.createElement('i');c.className='chip';c.style.left='210px';c.style.top='5px';$('#board').append(c);let lane=Math.random()*7|0;requestAnimationFrame(()=>{c.style.left=(20+lane*60)+'px';c.style.top='295px'});setTimeout(()=>{let m=[0,1,2,3,2,1,0][lane];change(m?b*m:-b);$('#result').textContent=m?`Lane ${lane+1}: won ${b*m} chips!`:`Outer lane: lost ${b} chips.`},1600)}}
function card(){let v=['A','2','3','4','5','6','7','8','9','10','J','Q','K'][Math.random()*13|0],s=['♠','♥','♦','♣'][Math.random()*4|0];return{v,s,n:({A:11,J:10,Q:10,K:10})[v]||+v}}function score(a){let n=a.reduce((x,c)=>x+c.n,0),z=a.filter(c=>c.v==='A').length;while(n>21&&z--)n-=10;return n}function drawCards(a){return a.map(c=>`<i class="playing-card ${c.s==='♥'||c.s==='♦'?'red':''}">${c.v}<br>${c.s}</i>`).join('')}
function blackjack(){let b,p,d,done=false;function render(){view.innerHTML=`<section class="felt"><button id="back">← Games</button><h2>♠ Blackjack</h2><div class="row">${bet()}<button id="deal" class="gold">Deal</button><button id="hit" disabled>Hit</button><button id="stand" disabled>Stand</button></div><h3>Dealer</h3><div id="dealer" class="cards"></div><h3>You <span id="total"></span></h3><div id="player" class="cards"></div><p id="result"></p></section>`;$('#back').onclick=lobby;$('#deal').onclick=deal;$('#hit').onclick=hit;$('#stand').onclick=stand}function paint(open){$('#dealer').innerHTML=open?drawCards(d):drawCards([d[0]])+'<i class="playing-card">?</i>';$('#player').innerHTML=drawCards(p);$('#total').textContent='('+score(p)+')'}function finish(t,delta){done=true;change(delta);$('#result').textContent=t;$('#hit').disabled=$('#stand').disabled=true}function deal(){b=getBet();if(!b)return toast('Enter a valid wager.');p=[card(),card()];d=[card(),card()];done=false;paint(false);$('#deal').disabled=true;$('#hit').disabled=$('#stand').disabled=false;if(score(p)===21)finish(`Blackjack! Won ${Math.floor(b*1.5)} chips.`,Math.floor(b*1.5))}function hit(){if(done)return;p.push(card());paint(false);if(score(p)>21)finish(`Bust. Lost ${b} chips.`,-b)}function stand(){if(done)return;while(score(d)<17)d.push(card());paint(true);let a=score(p),z=score(d);if(z>21||a>z)finish(`You win! Won ${b} chips.`,b);else if(a===z)finish('Push — wager returned.',0);else finish(`Dealer wins. Lost ${b} chips.`,-b)}render()}
function terminal(){panel('> Casino Console',`<div class="terminal panel"><p>Enter a code.</p><input id="code" placeholder="Code"><button id="execute">Execute</button><p id="result"></p></div>`);$('#execute').onclick=()=>{let c=$('#code').value.trim().toUpperCase();if(c==='DEVPERMS54321'){dev=true;localStorage.setItem('gambleDev','true');$('#result').textContent='Developer permissions enabled in this browser.';return}if(c==='JACKPOT1000'){change(1000);$('#result').textContent='Added 1,000 chips.';return}$('#result').textContent='Unknown code.'}}
function leaderboard(){panel('🏆 Leaderboard',`<p>Firebase leaderboard is disabled in this hotfix so guest play always works.</p><div class="leader"><span>1. You (local)</span><b>◈ ${Math.floor(chips).toLocaleString()}</b></div>`)}function shop(){let skins=['Classic','Ruby Velvet','Neon Night','Emerald Room','Royal Gold','Cyber Purple','Ocean Luxe','Sunset Club','Diamond Hall'];panel('🎨 Casino Cosmetics',`<p>Click a cosmetic to equip its accent color.</p><div class="shop-grid">${skins.map((s,i)=>`<button class="skin" data-s="${i}" style="--c:${['#ffd15d','#ff4165','#67e8f9','#60eaa4','#ffd64f','#c084fc','#57c7ff','#fb8c5d','#e8f2ff'][i]};--bg1:#203653"><b>${s}</b><br><small>Equip</small></button>`).join('')}</div>`);document.querySelectorAll('[data-s]').forEach(x=>x.onclick=()=>{document.documentElement.style.setProperty('--accent',x.style.getPropertyValue('--c'));toast('Cosmetic equipped')})}
